---
language: cpp
dist: bionic

addons:
  apt:
    update: false
    packages:
      - libboost-test-dev
      - libboost-program-options-dev
      - g++-8

env:
  - BUILD_TYPE=Release CXX=/usr/bin/g++-8

script:
  - set -e
  - cmake --DCMAKE_BUILD_TYPE=${BUILD_TYPE} .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package

deploy:
  - provider: bintray
    skip_cleanup: true
    file: bintray.json
    user: bergentroll
    edge: true
    on:
      branch: master
